"""9画面(設計書 §7.1)の view-model。

実体は `presentation/common/actions.py`(API facade と共有)。Web/TUI は
本モジュール経由で呼び、HTML/badge 等の画面固有加工が必要になったら
ここで薄いラッパを足す。Phase 2b で Web/TUI 削除までこの再公開を維持する。
"""

from __future__ import annotations

from abist_kb.presentation.common.actions import (
    batch_add,
    batch_edit,
    batch_remove,
    batch_run,
    batches_list,
    chat_ask,
    chat_history,
    chat_start,
    chat_stub,
    dashboard,
    document_delete,
    document_detail,
    document_update_metadata,
    documents_list,
    job_cancel,
    job_detail,
    job_retry,
    jobs_list,
    quality_run_backfill_metadata,
    quality_run_contradictions,
    quality_run_duplicates,
    quality_run_integrity,
    quality_stub,
    search,
    settings_diagnostics,
    source_add,
    source_edit,
    source_remove,
    source_test_connection,
    sources_list,
    visualization_deps,
    visualization_submit_render,
    visualization_validate,
)
from abist_kb.presentation.web.viewmodels.tokens import job_state_token

__all__ = [
    "batch_add",
    "batch_edit",
    "batch_remove",
    "batch_run",
    "batches_list",
    "chat_ask",
    "chat_history",
    "chat_start",
    "chat_stub",
    "dashboard",
    "document_delete",
    "document_detail",
    "document_update_metadata",
    "documents_list",
    "job_cancel",
    "job_detail",
    "job_retry",
    "jobs_list",
    "job_state_token",
    "quality_run_backfill_metadata",
    "quality_run_contradictions",
    "quality_run_duplicates",
    "quality_run_integrity",
    "quality_stub",
    "search",
    "settings_diagnostics",
    "source_add",
    "source_edit",
    "source_remove",
    "source_test_connection",
    "sources_list",
    "visualization_deps",
    "visualization_submit_render",
    "visualization_validate",
]
