"""API 向け facade: Application Service 直呼び(kb-admin と同型)。

`presentation/common/actions.py` の操作を再公開する薄い層。
`presentation/api/app.py` はここ経由でのみ業務操作へ到達し、
`web.viewmodels.screens` には依存しない。
"""

from __future__ import annotations

from abist_kb.presentation.common.actions import (
    batch_add,
    batch_edit,
    batch_remove,
    batch_run,
    batches_list,
    chat_ask,
    chat_history,
    chat_start,
    chat_stub,
    dashboard,
    document_delete,
    document_detail,
    document_update_metadata,
    documents_list,
    job_cancel,
    job_detail,
    job_retry,
    jobs_list,
    quality_run_backfill_metadata,
    quality_run_contradictions,
    quality_run_duplicates,
    quality_run_integrity,
    quality_stub,
    search,
    settings_diagnostics,
    source_add,
    source_edit,
    source_remove,
    source_test_connection,
    sources_list,
    video_approve,
    video_create,
    video_detail,
    video_list,
    video_request_public_review,
    video_run_qa,
    video_set_distribution,
    video_submit_render,
    visualization_deps,
    visualization_detail,
    visualization_list,
    visualization_submit_render,
    visualization_validate,
)

__all__ = [
    "batch_add",
    "batch_edit",
    "batch_remove",
    "batch_run",
    "batches_list",
    "chat_ask",
    "chat_history",
    "chat_start",
    "chat_stub",
    "dashboard",
    "document_delete",
    "document_detail",
    "document_update_metadata",
    "documents_list",
    "job_cancel",
    "job_detail",
    "job_retry",
    "jobs_list",
    "quality_run_backfill_metadata",
    "quality_run_contradictions",
    "quality_run_duplicates",
    "quality_run_integrity",
    "quality_stub",
    "search",
    "settings_diagnostics",
    "source_add",
    "source_edit",
    "source_remove",
    "source_test_connection",
    "sources_list",
    "video_approve",
    "video_create",
    "video_detail",
    "video_list",
    "video_request_public_review",
    "video_run_qa",
    "video_set_distribution",
    "video_submit_render",
    "visualization_deps",
    "visualization_detail",
    "visualization_list",
    "visualization_submit_render",
    "visualization_validate",
]
